### ISSUE TITLE
Error with API

### ISSUE THREAD

**Issue by apex2060** [webdev-sh/javascript-minifier.com#5]
Following the documentation I submit a minify api request and get the following error in response:
// Error : Cannot read property 'resolve_defines' of null
// Line  : undefined
// Col   : undefined

var options = {
		    method: 'POST',
		    uri:	`https://javascript-minifier.com/raw`,
		    formData: {
		        input: '...JS code here...'
		    },
		    headers: {
		        'Content-Type': 'application/x-www-form-urlencoded',
		        'Content-Length': request.body.input.length
		    }
		};
		console.log(options)
		http(options).then(result=>{
			response.send(result)
		}).catch(e=>{
			response.send(e)
		});

**Comment by vietnguyen09** [comment]
You shouldn't call the API via Ajax request, API should be called from the server code base.

**Comment by samyakbambole** [comment]
This is happening with me too

**Comment by samyakbambole** [comment]
I am using Curl

**Comment by chilts** [comment]
Take a look at the nodejs example on the site. This example works fine. https://javascript-minifier.com/nodejs

As @vietnguyen09 says, this doesn't work via an Ajax request, though it seems you have problems with your example code above anyway. (e.g. where does `result` come from?)
